---

- apt: name=elasticsearch state=latest update_cache=yes

- name: Update hostname.
  hostname: name={{ ansible_host }}

- name: Get the local-ipv4 address from the meta-data service.
  uri:
    url: "http://169.254.169.254/latest/meta-data/local-ipv4"
    return_content: yes
  register: local_ipv4

- name: Update /etc/hosts.
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ local_ipv4.content }} {{ ansible_host }}"
    insertbefore: "^# "
    line: "{{ local_ipv4.content }} {{ ansible_host }}"
    state: present

- stat: path=/usr/lib/systemd/system/elasticsearch.service
  register: elasticsearch_service

#1. /usr/lib/systemd/system/elasticsearch.yml => LimitMEMLOCK=infinity
#2. /etc/default/elasticsearch => MAX_LOCKED_MEMORY=unlimited
#3. /etc/elasticsearch/elasticsearch.yml => bootstrap.mlockall: true
#4. /etc/elasticsearch/jvm.options => -server before -Xms
#5. /etc/elasticsearch/jvm.options => -Xms... => -Xms<ES_HEAP_SIZE>
#6. /etc/elasticsearch/jvm.options => -Xmx... => -Xmx<ES_HEAP_SIZE>

- name: Update LimitMEMLOCK in elasticsearch.service.
  lineinfile:
    dest: /usr/lib/systemd/system/elasticsearch.service
    regexp: "^LimitMEMLOCK="
    insertafter: "^#LimitMEMLOCK="
    line: "LimitMEMLOCK=infinity"
    state: present
  when: elasticsearch_service.stat.exists == True

- name: Update LimitMEMLOCK in elasticsearch.service.
  lineinfile:
    dest: /usr/lib/systemd/system/elasticsearch.service
    regexp: "^MAX_LOCK_MEMORY="
    insertafter: "^#MAX_LOCK_MEMORY="
    line: "MAX_LOCK_MEMORY=unlimited"
    state: present

- name: JVM Memory uses half of the machine ram in gigabytes.
  set_fact:
    jvm_memory: "{{ ansible_memtotal_mb // 2000 }}g"
    
- name: Set minimum ram flag for jvm.
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "^-Xms"
    insertbefore: "^-Xms"
    line: "-Xms{{ jvm_memory }}"
    state: present

- name: Set maximum ram flag for jvm.
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "^-Xmx"
    insertbefore: "^-Xmx"
    line: "-Xmx{{ jvm_memory }}"
    state: present

- name: Add -server flag for jvm.
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "^-server"
    insertbefore: "^-Xms"
    line: "-server"
    state: present

- name: Start Elasticsearch on boot.
  command: update-rc.d elasticsearch defaults 95 10

- include: elasticsearch.yml