---
# This playbook creates the MVP ELK system for LSST SQuaRE.

- hosts: kibana
  remote_user: vagrant
  become: yes
  gather_facts: yes
  roles:
  - role: kibana
  - role: jdauphant.ssl-certs
    ssl_certs_common_name: "lsst.codes"
    ssl_certs_generate_dh_param: yes
  - role: geerlingguy.nginx
    nginx_ppa_use: yes
    nginx_worker_processes: "4"
    nginx_vhosts:
      - listen: "443 ssl"
        server_name: "logging.lsst.codes"
        access_log: "/var/log/nginx/kibana_access.log"
        error_log: "/var/log/nginx/kibana_error.log"
        extra_parameters: |
          ssl_certificate     /etc/ssl/lsst.codes/lsst.codes.pem;
          ssl_certificate_key /etc/ssl/lsst.codes/lsst.codes.key;
          ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
          location / {
            proxy_pass http://localhost:5601;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;        
          }
    nginx_remove_default_vhost: yes